### PR TITLE
GHC 8 Compatibility

### PR DESCRIPTION
**Pull request by cocreature**
Adds compatibilty with GHC 8

### CODE REVIEW

**Comment by bscarlet** [comment]
Please include descriptions with pull requests.

**Comment by cocreature** [comment]
While I agree in general, a description called “Adds compatibilty with GHC 8” seems a bit redundant when the PR is called “GHC 8 Compatibility”.

**Comment by bscarlet** [comment]
Do I understand right that the intended consequence of this change is reflected in the change of the travis GHC-8 build result from "job errored" to "job failed"?

**Comment by cocreature** [comment]
Yep, we still need the metadata changes and maybe also the flag changes to fix the build.

**Pull request merged**
